### ISSUE TITLE
Questions about IVRDriverDirectModeComponent api

### ISSUE THREAD

**Issue by LoSealL** [sencercoltu/openvr-customhmd#2]
Hi @sencercoltu. I'm a hmd DIYer, I want to say thanks because your work inspire me a lot!
Here I want to start a new thread to discuss about the interface `IVRDriverDirectModeComponent`, which is the most confused api in openvr I think.

First of all, let me summarize my works on it. I want to manipulate the renderbuffers for each eye, such as dump/copy/stream them, so I'd like openvr offer some api to access them, and that is what exactly `IVRDriverDirectModeComponent` does.
However, `IVRDriverDirectModeComponent` is hard to understand.
ASAK, you should enable `UsesDriverDirectMode` as true and return both `IsDisplayOnDesktop()` and `IsDisplayRealDisplay()` false to get `IVRDriverDirectModeComponent` involved.

What's more, I complied your code and dump every API logs. What I saw is that in vrcompositor, each eye will call `CreateSwapTextureSet()` to create 3 sharedhandles.
And `GetNextSwapTextureSetIndex()` is meant to get the next rendered texture for each eye. But in your code, every time calls `GetNextSwapTextureSetIndex` pass in the same shared handle, while the rest two shared textures never used.
Hence I guess `GetNextSwapTextureSetIndex`'s first argument is the current render texture, and you need to get the next texture's index but not this one's. So I modify your code as:
`(*pIndices)[i] = (tl.pData->Index + 1) % 3;`
And at last I can see every shared textures get used.

Hope to get your reply about these gossip and we may discuss further?

BR

**Comment by sencercoltu** [comment]
Hi @LoSealL,
Glad to see people getting inspired. Thanks for the suggestion about the GetNextSwapTextureSetIndex function, that's probably how it's intended to work. I've minimal knowledge about 3D and VR stuff, most I get working by experimenting :)
The latest commit of the driver includes code for dump/copy/stream the eye frames. I'm currently joining both eyes in a single SBS (RGBA or BGRA) frame, convert it to YUV and stream it to an android device using ffmpeg api and the udp protocol, using the IVRDriverDirectModeComponent functions. I'm still trying to minimize the latency..

**Comment by LoSealL** [comment]
@sencercoltu.
Yeah, I have been working for a whole year on this subject (but without using openvr). I use Unity to create a simple game and dump, encode, stream to a client, while the client decode, do timewarp and flush the texture to screen. I target on WiFi 802.11ac so I choose to encode texture into AVC bitstream. My letency is around 50ms end to end.
Since you are using YUV to stream, so I guess you are targeting on Wigig 60GHz?

**Comment by LoSealL** [comment]
@sencercoltu 
I have questions about `IVRDriverDirectModeComponent`.
- You lock every api call by a mutex, is it necessary?
- Have you test with enough steamvr games?
- What's the `present` exactly do in this interface?

As for the 2nd question, I have more to discuss.

The `IVRDriverDirectModeComponent` API is very likely to Oculus API (don't know if you are familiar with Oculus). In Oculus API though, `submitLayer` is called to composite multiple layers to a final texture.
While in the openvr, is `SubmitLayer` doing the same thing or something else? If so, you may not get the final texture in this api. (However if the app has only one layer, there is no problem)

**Comment by sencercoltu** [comment]
> You lock every api call by a mutex, is it necessary?

Probably not necessary everywhere. I was getting exceptions while iterating over the texture map in other threads, so I just synchronized the map access completely to be safe.

> Have you test with enough steamvr games?

I haven't tried any games yet by streaming to a remote display (IVRDriverDirectModeComponent). But all VR compatible games I've tried (about 230 titles in Steam) ran on my DIY pre-Sony headset without, (with SteamVR's direct mode enabled,). Well, I've build only one controller so far, and I'm still working on positional tracking, so I can just say that the display part is working correctly. 

> What's the present exactly do in this interface?

I have no idea. Maybe after all layers are submitted with SubmitLayer, the Present function is called and you composite your final texture from all layers received. ??

**Comment by LoSealL** [comment]
Thanks for your kindly reply.

Today I have tested `Present` and found that its argument `SharedTextureHandle_t` is not used. I also noticed that OpenVR's developer claims to implement a new `vr::IVirtualDisplay` interface for remote displaying, and you can find this name in log file `vrclient_compositor.txt` after today's update (1771318).

What's more, if you start a game (such as tutorial for example), vrserver will call createswaptextureset several times with different size. (My recommended render size is 1024x1024, but the created swap texture sizes are 1024x1024, 2048x1024 and 13??x14??, respectively) So I guess we have to resample these textures to the recommended size? Otherwise it can't be encoded and decoded at all! 

What are you going to do with this?

**Comment by sencercoltu** [comment]
Seems Createtextureswapset is called for each process' allocated textures
separately. The process of is one of the arguments. When a game runs, the
function is also called for the games textures.
I am currently using ffmpegs swscaler, to convert pixel format and scale to
the stream resolution.
I also think switching to MFT, which supports AMD, NV and Intel hardware
encoding.  Looking for a way to let the GPU do the scaling and pixformat
conversion.

On Apr 25, 2017 5:55 PM, "Tang, Wenyi" <notifications@github.com> wrote:

Thanks for your kindly reply.

Today I have tested Present and found that its argument
SharedTextureHandle_t is not used. I also noticed that OpenVR's developer
claims to implement a new vr::IVirtualDisplay interface for remote
displaying, and you can find this name in log file vrclient_compositor.txt
after today's update (1771318).

What's more, if you start a game (such as tutorial for example), vrserver
will call createswaptextureset several times with different size. (My
recommended render size is 1024x1024, but the created swap texture sizes
are 1024x1024, 2048x1024 and 13??x14??, respectively) So I guess we have to
resample these textures to the recommended size? Otherwise it can't be
encoded and decoded at all!

What are you going to do with this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sencercoltu/openvr-customhmd/issues/2#issuecomment-297056834>,
or mute the thread

**Comment by LoSealL** [comment]
Oh, I see. My concern is that using ffmpeg resampling will cause big latency (Haven't tested though).
So my way is to firstly use shader to resample layers into final rendertarget and using hardware codec api to do the encode stuff...
Still struggle to write my shaders...

**Comment by LoSealL** [comment]
I have dumped tutorail shared textures (My WindowBound is 2048x1024, and render size is 1024x1024)
And it's scary....
![Dump](http://i2.muimg.com/567571/3ec870958478c3e1.jpg)
